### ISSUE TITLE
1.19.2?

### ISSUE THREAD

**Issue by Reffler** [fxmorin/MoreCullingExtra#2]
Thanks for making this mod!

Is there a 1.19.2 version?

Cheers! :)

**Comment by fxmorin** [comment]
I don't have the time to update another version

**Comment by DaveyL2013** [comment]
Here I backported it and it seems to work perfectly without any real changes https://github.com/DaveyL2013/MoreCullingExtra/releases

**Comment by fxmorin** [comment]
@DaveyL2013 Oh wow didn't realize how easy it would have been to port. You can make a PR to this branch: https://github.com/fxmorin/MoreCullingExtra/tree/1.19.2
